package com.innertrack.model;

import java.util.List;

/**
 * Result of the ML-based recommendation generated by the model.
 */
public class AIRecommandation {

    private String cluster; // "Fragile", "Stable", "Résilient"
    private double[] probabilites; // [p_Fragile, p_Stable, p_Résilient]
    private int scoreConfiance; // Confidence % (0-100)
    private double[] features; // The 7 extracted features
    private String analyseGlobale; // Narrative analysis text
    private List<Habitude> habitudes; // Personalized recommendations
    private String planSemaine; // 7-day action plan
    private List<String> alertes; // Attention points

    // ── Inner class Habitude ──
    public static class Habitude {
        public String emoji;
        public String titre;
        public String description;
        public String frequence;
        public String categorie;
        public String impact; // "CRITIQUE", "Élevé", "Moyen", "Fort", "Maintien"
    }

    // ── Getters & Setters ──
    public String getCluster() {
        return cluster;
    }

    public double[] getProbabilites() {
        return probabilites;
    }

    public int getScoreConfiance() {
        return scoreConfiance;
    }

    public double[] getFeatures() {
        return features;
    }

    public String getAnalyseGlobale() {
        return analyseGlobale;
    }

    public List<Habitude> getHabitudes() {
        return habitudes;
    }

    public String getPlanSemaine() {
        return planSemaine;
    }

    public List<String> getAlertes() {
        return alertes;
    }

    public void setCluster(String v) {
        cluster = v;
    }

    public void setProbabilites(double[] v) {
        probabilites = v;
    }

    public void setScoreConfiance(int v) {
        scoreConfiance = v;
    }

    public void setFeatures(double[] v) {
        features = v;
    }

    public void setAnalyseGlobale(String v) {
        analyseGlobale = v;
    }

    public void setHabitudes(List<Habitude> v) {
        habitudes = v;
    }

    public void setPlanSemaine(String v) {
        planSemaine = v;
    }

    public void setAlertes(List<String> v) {
        alertes = v;
    }

    /** Returns the color label based on the cluster */
    public String getCouleurCluster() {
        if (cluster == null)
            return "#888888";
        return switch (cluster) {
            case "Fragile" -> "#e74c3c";
            case "Stable" -> "#f39c12";
            case "Résilient" -> "#27ae60";
            default -> "#888888";
        };
    }

    /** Returns the emoji for the cluster */
    public String getEmojiCluster() {
        if (cluster == null)
            return "❓";
        return switch (cluster) {
            case "Fragile" -> "🔴";
            case "Stable" -> "🟡";
            case "Résilient" -> "🟢";
            default -> "❓";
        };
    }
}
