<?php

namespace ContainerADEKO1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Wx1oO5DService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wx1oO5D' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wx1oO5D'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conversation' => ['privates', '.errored..service_locator.wx1oO5D.App\\Entity\\Conversation', NULL, 'Cannot autowire service ".service_locator.wx1oO5D": it needs an instance of "App\\Entity\\Conversation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'conversation' => 'App\\Entity\\Conversation',
        ]);
    }
}
