<?php

namespace ContainerADEKO1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J1cJA1MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j1cJA1M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j1cJA1M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'report' => ['privates', '.errored..service_locator.j1cJA1M.App\\Entity\\Report', NULL, 'Cannot autowire service ".service_locator.j1cJA1M": it needs an instance of "App\\Entity\\Report" but this type has been excluded in "config/services.yaml".'],
        ], [
            'report' => 'App\\Entity\\Report',
        ]);
    }
}
