<?php

namespace ContainerADEKO1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1awqb7hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1awqb7h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'comment' => ['privates', '.errored..service_locator.1awqb7h.App\\Entity\\CommunityComment', NULL, 'Cannot autowire service ".service_locator.1awqb7h": it needs an instance of "App\\Entity\\CommunityComment" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'comment' => 'App\\Entity\\CommunityComment',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.1awqb7h'])) {
            return $container->privates['.service_locator.1awqb7h'];
        }

        return $container->privates['.service_locator.1awqb7h'] = $instance;
    }
}
