<?php

namespace ContainerADEKO1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OYWGn7RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oYWGn7R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oYWGn7R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.oYWGn7R.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.oYWGn7R": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'paRepository' => ['privates', 'App\\Repository\\PathArticleRepository', 'getPathArticleRepositoryService', true],
            'pathRepository' => ['privates', 'App\\Repository\\LearningPathRepository', 'getLearningPathRepositoryService', true],
            'tagRepository' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'paRepository' => 'App\\Repository\\PathArticleRepository',
            'pathRepository' => 'App\\Repository\\LearningPathRepository',
            'tagRepository' => 'App\\Repository\\TagRepository',
        ]);
    }
}
