<?php

namespace ContainerADEKO1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WrYbiVSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wrYbiVS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'path' => ['privates', '.errored..service_locator.wrYbiVS.App\\Entity\\LearningPath', NULL, 'Cannot autowire service ".service_locator.wrYbiVS": it needs an instance of "App\\Entity\\LearningPath" but this type has been excluded in "config/services.yaml".'],
        ], [
            'articleRepo' => 'App\\Repository\\ArticleRepository',
            'em' => '?',
            'path' => 'App\\Entity\\LearningPath',
        ]);

        if (isset($container->privates['.service_locator.wrYbiVS'])) {
            return $container->privates['.service_locator.wrYbiVS'];
        }

        return $container->privates['.service_locator.wrYbiVS'] = $instance;
    }
}
