<?php

namespace ContainerADEKO1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Mi6ClI3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mi6ClI3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventRepo' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
            'inscription' => ['privates', '.errored..service_locator.mi6ClI3.App\\Entity\\Inscription', NULL, 'Cannot autowire service ".service_locator.mi6ClI3": it needs an instance of "App\\Entity\\Inscription" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'eventRepo' => 'App\\Repository\\EventRepository',
            'inscription' => 'App\\Entity\\Inscription',
        ]);

        if (isset($container->privates['.service_locator.mi6ClI3'])) {
            return $container->privates['.service_locator.mi6ClI3'];
        }

        return $container->privates['.service_locator.mi6ClI3'] = $instance;
    }
}
