<?php

namespace ContainerADEKO1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FqEzgDBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fqEzgDB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fqEzgDB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repo' => ['privates', 'App\\Repository\\LearningPathRepository', 'getLearningPathRepositoryService', true],
        ], [
            'repo' => 'App\\Repository\\LearningPathRepository',
        ]);
    }
}
