<?php

namespace ContainerADEKO1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H3SHRalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h3SHRal' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h3SHRal'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entree' => ['privates', '.errored..service_locator.h3SHRal.App\\Entity\\Journal\\EntreeJournal', NULL, 'Cannot autowire service ".service_locator.h3SHRal": it needs an instance of "App\\Entity\\Journal\\EntreeJournal" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entree' => 'App\\Entity\\Journal\\EntreeJournal',
        ]);
    }
}
