<?php

namespace ContainerADEKO1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCommunityCommentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1awqb7h.App\Entity\CommunityComment' shared service.
     *
     * @return \App\Entity\CommunityComment
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.1awqb7h": it needs an instance of "App\\Entity\\CommunityComment" but this type has been excluded in "config/services.yaml".');
    }
}
