<?php

namespace ContainerADEKO1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPdfExporterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PdfExporter' shared autowired service.
     *
     * @return \App\Service\PdfExporter
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PdfExporter.php';

        return $container->privates['App\\Service\\PdfExporter'] = new \App\Service\PdfExporter();
    }
}
