<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WBCwxMiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wBCwxMi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'event' => ['privates', '.errored..service_locator.wBCwxMi.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.wBCwxMi": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".'],
            'inscRepo' => ['privates', 'App\\Repository\\InscriptionRepository', 'getInscriptionRepositoryService', true],
        ], [
            'em' => '?',
            'event' => 'App\\Entity\\Event',
            'inscRepo' => 'App\\Repository\\InscriptionRepository',
        ]);

        if (isset($container->privates['.service_locator.wBCwxMi'])) {
            return $container->privates['.service_locator.wBCwxMi'];
        }

        return $container->privates['.service_locator.wBCwxMi'] = $instance;
    }
}
