<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U2bJXgzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u2bJXgz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.u2bJXgz.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.u2bJXgz": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tagRepository' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'article' => 'App\\Entity\\Article',
            'em' => '?',
            'tagRepository' => 'App\\Repository\\TagRepository',
        ]);

        if (isset($container->privates['.service_locator.u2bJXgz'])) {
            return $container->privates['.service_locator.u2bJXgz'];
        }

        return $container->privates['.service_locator.u2bJXgz'] = $instance;
    }
}
