<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PtjrVLNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ptjrVLN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'article' => ['privates', '.errored..service_locator.ptjrVLN.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.ptjrVLN": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'pdf' => ['services', 'Knp\\Snappy\\Pdf', 'getPdfService', true],
            'twig' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'article' => 'App\\Entity\\Article',
            'pdf' => 'Knp\\Snappy\\Pdf',
            'twig' => '?',
        ]);

        if (isset($container->privates['.service_locator.ptjrVLN'])) {
            return $container->privates['.service_locator.ptjrVLN'];
        }

        return $container->privates['.service_locator.ptjrVLN'] = $instance;
    }
}
