<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3F34mDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3F34m_d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventRepo' => ['privates', 'App\\Repository\\EventRepository', 'getEventRepositoryService', true],
        ], [
            'em' => '?',
            'eventRepo' => 'App\\Repository\\EventRepository',
        ]);

        if (isset($container->privates['.service_locator.3F34m_d'])) {
            return $container->privates['.service_locator.3F34m_d'];
        }

        return $container->privates['.service_locator.3F34m_d'] = $instance;
    }
}
