<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EsAKHBHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.esAKHBH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'inscription' => ['privates', '.errored..service_locator.esAKHBH.App\\Entity\\Inscription', NULL, 'Cannot autowire service ".service_locator.esAKHBH": it needs an instance of "App\\Entity\\Inscription" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'inscription' => 'App\\Entity\\Inscription',
        ]);

        if (isset($container->privates['.service_locator.esAKHBH'])) {
            return $container->privates['.service_locator.esAKHBH'];
        }

        return $container->privates['.service_locator.esAKHBH'] = $instance;
    }
}
