<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DdNaYWTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DdNaYWT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.DdNaYWT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'aiInsight' => ['privates', 'App\\Service\\AiInsightService', 'getAiInsightServiceService', true],
            'article' => ['privates', '.errored..service_locator.DdNaYWT.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.DdNaYWT": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".'],
            'freesound' => ['privates', 'App\\Service\\FreeSoundService', 'getFreeSoundServiceService', true],
            'openLibrary' => ['privates', 'App\\Service\\OpenLibraryService', 'getOpenLibraryServiceService', true],
            'paRepository' => ['privates', 'App\\Repository\\PathArticleRepository', 'getPathArticleRepositoryService', true],
            'pathRepository' => ['privates', 'App\\Repository\\LearningPathRepository', 'getLearningPathRepositoryService', true],
            'tagRepository' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'aiInsight' => 'App\\Service\\AiInsightService',
            'article' => 'App\\Entity\\Article',
            'freesound' => 'App\\Service\\FreeSoundService',
            'openLibrary' => 'App\\Service\\OpenLibraryService',
            'paRepository' => 'App\\Repository\\PathArticleRepository',
            'pathRepository' => 'App\\Repository\\LearningPathRepository',
            'tagRepository' => 'App\\Repository\\TagRepository',
        ]);
    }
}
