<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JfelCFHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jfelCFH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jfelCFH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'event' => ['privates', '.errored..service_locator.jfelCFH.App\\Entity\\Event', NULL, 'Cannot autowire service ".service_locator.jfelCFH": it needs an instance of "App\\Entity\\Event" but this type has been excluded in "config/services.yaml".'],
            'inscRepo' => ['privates', 'App\\Repository\\InscriptionRepository', 'getInscriptionRepositoryService', true],
        ], [
            'event' => 'App\\Entity\\Event',
            'inscRepo' => 'App\\Repository\\InscriptionRepository',
        ]);
    }
}
