<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HjIqL60Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HjIqL60' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailSender' => ['privates', 'App\\Service\\EmailSender', 'getEmailSenderService', true],
        ], [
            'emailSender' => 'App\\Service\\EmailSender',
        ]);

        if (isset($container->privates['.service_locator.HjIqL60'])) {
            return $container->privates['.service_locator.HjIqL60'];
        }

        return $container->privates['.service_locator.HjIqL60'] = $instance;
    }
}
