<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAiInsightServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\AiInsightService' shared autowired service.
     *
     * @return \App\Service\AiInsightService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'AiInsightService.php';

        return $container->privates['App\\Service\\AiInsightService'] = new \App\Service\AiInsightService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)));
    }
}
