<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEntreeJournalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.h3SHRal.App\Entity\Journal\EntreeJournal' shared service.
     *
     * @return \App\Entity\Journal\EntreeJournal
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.h3SHRal": it needs an instance of "App\\Entity\\Journal\\EntreeJournal" but this type has been excluded in "config/services.yaml".');
    }
}
