<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFreeSoundServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\FreeSoundService' shared autowired service.
     *
     * @return \App\Service\FreeSoundService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'FreeSoundService.php';

        return $container->privates['App\\Service\\FreeSoundService'] = new \App\Service\FreeSoundService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $container->getEnv('FREESOUND_API_KEY'));
    }
}
