<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHabitudeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.y5QrzdZ.App\Entity\Journal\Habitude' shared service.
     *
     * @return \App\Entity\Journal\Habitude
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.y5QrzdZ": it needs an instance of "App\\Entity\\Journal\\Habitude" but this type has been excluded in "config/services.yaml".');
    }
}
