<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLearningPathService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YCqoOEL.App\Entity\LearningPath' shared service.
     *
     * @return \App\Entity\LearningPath
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.YCqoOEL": it needs an instance of "App\\Entity\\LearningPath" but this type has been excluded in "config/services.yaml".');
    }
}
