<?php

namespace ContainerYWKud5H;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReportService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.j1cJA1M.App\Entity\Report' shared service.
     *
     * @return \App\Entity\Report
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.j1cJA1M": it needs an instance of "App\\Entity\\Report" but this type has been excluded in "config/services.yaml".');
    }
}
