<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYWKud5H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYWKud5H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYWKud5H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYWKud5H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYWKud5H\App_KernelDevDebugContainer([
    'container.build_hash' => 'YWKud5H',
    'container.build_id' => 'fa98b1b3',
    'container.build_time' => 1776856346,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYWKud5H');
