<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408075821 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE evenement (id INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) NOT NULL, description LONGTEXT NOT NULL, date_debut DATETIME NOT NULL, date_fin DATETIME NOT NULL, lieu VARCHAR(255) NOT NULL, statut VARCHAR(50) NOT NULL, nombre_participants INT DEFAULT NULL, nombre_max_participants INT DEFAULT NULL, image_url VARCHAR(500) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, created_by INT NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE ai_recommandation DROP FOREIGN KEY `FK_AI_REC_TEST`');
        $this->addSql('ALTER TABLE ai_recommandation DROP FOREIGN KEY `FK_AI_REC_USER`');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY `fk_article_categorie`');
        $this->addSql('ALTER TABLE article DROP FOREIGN KEY `fk_article_user`');
        $this->addSql('ALTER TABLE article_tag DROP FOREIGN KEY `fk_at_article`');
        $this->addSql('ALTER TABLE article_tag DROP FOREIGN KEY `fk_at_tag`');
        $this->addSql('ALTER TABLE community_comment DROP FOREIGN KEY `fk_cc_parent`');
        $this->addSql('ALTER TABLE community_comment DROP FOREIGN KEY `fk_cc_user`');
        $this->addSql('ALTER TABLE community_reaction DROP FOREIGN KEY `fk_cr_comment`');
        $this->addSql('ALTER TABLE community_reaction DROP FOREIGN KEY `fk_cr_user`');
        $this->addSql('ALTER TABLE event DROP FOREIGN KEY `event_ibfk_1`');
        $this->addSql('ALTER TABLE habittracker DROP FOREIGN KEY `fk_habit_journal`');
        $this->addSql('ALTER TABLE habittracker DROP FOREIGN KEY `fk_habit_user`');
        $this->addSql('ALTER TABLE historique_resultat DROP FOREIGN KEY `FK_HIST_TEST`');
        $this->addSql('ALTER TABLE historique_resultat DROP FOREIGN KEY `FK_HIST_USER`');
        $this->addSql('ALTER TABLE inscription DROP FOREIGN KEY `inscription_ibfk_1`');
        $this->addSql('ALTER TABLE journal_emotionnel DROP FOREIGN KEY `fk_journal_user`');
        $this->addSql('ALTER TABLE learning_path DROP FOREIGN KEY `fk_lp_user`');
        $this->addSql('ALTER TABLE path_article DROP FOREIGN KEY `fk_pa_article`');
        $this->addSql('ALTER TABLE path_article DROP FOREIGN KEY `fk_pa_path`');
        $this->addSql('ALTER TABLE question DROP FOREIGN KEY `FK_QUESTION_TEST`');
        $this->addSql('ALTER TABLE reponse DROP FOREIGN KEY `FK_REPONSE_QUESTION`');
        $this->addSql('ALTER TABLE reponse_utilisateur DROP FOREIGN KEY `FK_RU_QUESTION`');
        $this->addSql('ALTER TABLE reponse_utilisateur DROP FOREIGN KEY `FK_RU_REPONSE`');
        $this->addSql('ALTER TABLE reponse_utilisateur DROP FOREIGN KEY `FK_RU_USER`');
        $this->addSql('ALTER TABLE resultat DROP FOREIGN KEY `FK_RESULTAT_TEST`');
        $this->addSql('ALTER TABLE resultat DROP FOREIGN KEY `FK_RESULTAT_USER`');
        $this->addSql('ALTER TABLE test_psychologique DROP FOREIGN KEY `FK_TEST_TYPE`');
        $this->addSql('ALTER TABLE tranche_resultat DROP FOREIGN KEY `FK_TRANCHE_TEST`');
        $this->addSql('DROP TABLE ai_recommandation');
        $this->addSql('DROP TABLE article');
        $this->addSql('DROP TABLE article_tag');
        $this->addSql('DROP TABLE categorie');
        $this->addSql('DROP TABLE community_comment');
        $this->addSql('DROP TABLE community_reaction');
        $this->addSql('DROP TABLE event');
        $this->addSql('DROP TABLE habittracker');
        $this->addSql('DROP TABLE historique_resultat');
        $this->addSql('DROP TABLE inscription');
        $this->addSql('DROP TABLE journal_emotionnel');
        $this->addSql('DROP TABLE learning_path');
        $this->addSql('DROP TABLE path_article');
        $this->addSql('DROP TABLE question');
        $this->addSql('DROP TABLE reponse');
        $this->addSql('DROP TABLE reponse_utilisateur');
        $this->addSql('DROP TABLE resultat');
        $this->addSql('DROP TABLE tag');
        $this->addSql('DROP TABLE test_psychologique');
        $this->addSql('DROP TABLE tranche_resultat');
        $this->addSql('DROP TABLE type_event');
        $this->addSql('DROP TABLE type_test');
        $this->addSql('ALTER TABLE blocked_user DROP FOREIGN KEY `fk_block_client`');
        $this->addSql('ALTER TABLE blocked_user DROP FOREIGN KEY `fk_block_therapist`');
        $this->addSql('DROP INDEX uq_block_pair ON blocked_user');
        $this->addSql('ALTER TABLE blocked_user DROP FOREIGN KEY `fk_block_therapist`');
        $this->addSql('ALTER TABLE blocked_user CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE blocked_user ADD CONSTRAINT FK_718E113719EB6921 FOREIGN KEY (client_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE blocked_user ADD CONSTRAINT FK_718E113743E8B094 FOREIGN KEY (therapist_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX fk_block_therapist ON blocked_user');
        $this->addSql('CREATE INDEX IDX_718E113743E8B094 ON blocked_user (therapist_id)');
        $this->addSql('ALTER TABLE blocked_user ADD CONSTRAINT `fk_block_therapist` FOREIGN KEY (therapist_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE chat_lock DROP FOREIGN KEY `fk_cl_admin`');
        $this->addSql('ALTER TABLE chat_lock DROP FOREIGN KEY `fk_cl_user`');
        $this->addSql('DROP INDEX idx_cl_user ON chat_lock');
        $this->addSql('DROP INDEX fk_cl_admin ON chat_lock');
        $this->addSql('ALTER TABLE chat_lock CHANGE locked_at locked_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE chat_lock ADD CONSTRAINT FK_2113064FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE client_profile DROP FOREIGN KEY `fk_client_user`');
        $this->addSql('ALTER TABLE client_profile DROP FOREIGN KEY `fk_client_user`');
        $this->addSql('ALTER TABLE client_profile CHANGE bio bio LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE client_profile ADD CONSTRAINT FK_D36AEE72A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX user_id ON client_profile');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D36AEE72A76ED395 ON client_profile (user_id)');
        $this->addSql('ALTER TABLE client_profile ADD CONSTRAINT `fk_client_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact_request DROP FOREIGN KEY `fk_cr_client`');
        $this->addSql('ALTER TABLE contact_request DROP FOREIGN KEY `fk_cr_therapist`');
        $this->addSql('ALTER TABLE contact_request DROP FOREIGN KEY `fk_cr_client`');
        $this->addSql('ALTER TABLE contact_request DROP FOREIGN KEY `fk_cr_therapist`');
        $this->addSql('ALTER TABLE contact_request CHANGE message message LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE contact_request ADD CONSTRAINT FK_A1B8AE1E19EB6921 FOREIGN KEY (client_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE contact_request ADD CONSTRAINT FK_A1B8AE1E43E8B094 FOREIGN KEY (therapist_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX fk_cr_client ON contact_request');
        $this->addSql('CREATE INDEX IDX_A1B8AE1E19EB6921 ON contact_request (client_id)');
        $this->addSql('DROP INDEX fk_cr_therapist ON contact_request');
        $this->addSql('CREATE INDEX IDX_A1B8AE1E43E8B094 ON contact_request (therapist_id)');
        $this->addSql('ALTER TABLE contact_request ADD CONSTRAINT `fk_cr_client` FOREIGN KEY (client_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact_request ADD CONSTRAINT `fk_cr_therapist` FOREIGN KEY (therapist_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY `fk_conv_client`');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY `fk_conv_therapist`');
        $this->addSql('DROP INDEX uq_conv ON conversation');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY `fk_conv_therapist`');
        $this->addSql('ALTER TABLE conversation CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E919EB6921 FOREIGN KEY (client_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E943E8B094 FOREIGN KEY (therapist_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX fk_conv_therapist ON conversation');
        $this->addSql('CREATE INDEX IDX_8A8E26E943E8B094 ON conversation (therapist_id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT `fk_conv_therapist` FOREIGN KEY (therapist_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY `fk_msg_conv`');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY `fk_msg_sender`');
        $this->addSql('DROP INDEX idx_msg_conv ON message');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY `fk_msg_sender`');
        $this->addSql('ALTER TABLE message CHANGE content content LONGTEXT NOT NULL, CHANGE sent_at sent_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F9AC0396 FOREIGN KEY (conversation_id) REFERENCES conversation (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX fk_msg_sender ON message');
        $this->addSql('CREATE INDEX IDX_B6BD307FF624B39D ON message (sender_id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT `fk_msg_sender` FOREIGN KEY (sender_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY `fk_notif_user`');
        $this->addSql('DROP INDEX idx_notif_user ON notification');
        $this->addSql('ALTER TABLE notification CHANGE body body LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE password_reset_codes DROP FOREIGN KEY `fk_reset_user`');
        $this->addSql('ALTER TABLE password_reset_codes DROP FOREIGN KEY `fk_reset_user`');
        $this->addSql('ALTER TABLE password_reset_codes CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE password_reset_codes ADD CONSTRAINT FK_D1E1C4C0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX idx_reset_user ON password_reset_codes');
        $this->addSql('CREATE INDEX IDX_D1E1C4C0A76ED395 ON password_reset_codes (user_id)');
        $this->addSql('ALTER TABLE password_reset_codes ADD CONSTRAINT `fk_reset_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY `fk_report_reported`');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY `fk_report_reporter`');
        $this->addSql('DROP INDEX idx_report_status ON report');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY `fk_report_reported`');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY `fk_report_reporter`');
        $this->addSql('ALTER TABLE report CHANGE details details LONGTEXT DEFAULT NULL, CHANGE context context VARCHAR(20) DEFAULT \'MESSAGING\' NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F778494BDEEB6 FOREIGN KEY (reported_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX idx_report_reporter ON report');
        $this->addSql('CREATE INDEX IDX_C42F7784E1CFE6F5 ON report (reporter_id)');
        $this->addSql('DROP INDEX fk_report_reported ON report');
        $this->addSql('CREATE INDEX IDX_C42F778494BDEEB6 ON report (reported_id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT `fk_report_reported` FOREIGN KEY (reported_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT `fk_report_reporter` FOREIGN KEY (reporter_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE therapist_profile DROP FOREIGN KEY `fk_therapist_user`');
        $this->addSql('ALTER TABLE therapist_profile DROP FOREIGN KEY `fk_therapist_user`');
        $this->addSql('ALTER TABLE therapist_profile DROP session_rate, DROP available_days, CHANGE bio bio LONGTEXT DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE therapist_profile ADD CONSTRAINT FK_12039482A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('DROP INDEX user_id ON therapist_profile');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_12039482A76ED395 ON therapist_profile (user_id)');
        $this->addSql('ALTER TABLE therapist_profile ADD CONSTRAINT `fk_therapist_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE user_settings DROP FOREIGN KEY `FK_SETTINGS_USER`');
        $this->addSql('ALTER TABLE user_settings CHANGE theme theme VARCHAR(5) DEFAULT \'LIGHT\' NOT NULL, CHANGE font_size font_size VARCHAR(6) DEFAULT \'NORMAL\' NOT NULL, CHANGE language language VARCHAR(2) DEFAULT \'FR\' NOT NULL');
        $this->addSql('ALTER TABLE user_settings ADD CONSTRAINT FK_5C844C5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ai_recommandation (id_recommandation INT AUTO_INCREMENT NOT NULL, id_utilisateur INT NOT NULL, id_test INT NOT NULL, cluster_profil VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, confiance DOUBLE PRECISION NOT NULL, habitudes_suggerees JSON DEFAULT NULL, plan_action JSON DEFAULT NULL, alertes_critiques JSON DEFAULT NULL, date_generation DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX IDX_AI_REC_TEST (id_test), INDEX IDX_AI_REC_USER (id_utilisateur), PRIMARY KEY (id_recommandation)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE article (id_Article INT AUTO_INCREMENT NOT NULL, titre VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, contenu TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, auteur_user_id INT NOT NULL, datePublication DATE NOT NULL, id_categorie INT DEFAULT NULL, readability VARCHAR(20) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX fk_article_categorie (id_categorie), INDEX fk_article_user (auteur_user_id), PRIMARY KEY (id_Article)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE article_tag (id_article INT NOT NULL, id_tag INT NOT NULL, INDEX fk_at_tag (id_tag), INDEX IDX_919694F9DCA7A716 (id_article), PRIMARY KEY (id_article, id_tag)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE categorie (id_categorie INT AUTO_INCREMENT NOT NULL, nom VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY (id_categorie)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE community_comment (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, content VARCHAR(500) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, modified TINYINT DEFAULT 0 NOT NULL, parent_id INT DEFAULT NULL, title VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX idx_cc_parent (parent_id), INDEX idx_cc_user (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE community_reaction (user_id INT NOT NULL, comment_id INT NOT NULL, reaction VARCHAR(8) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, INDEX idx_cr_comment (comment_id), INDEX IDX_5691C2D0A76ED395 (user_id), PRIMARY KEY (user_id, comment_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE event (id_event INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_event DATE NOT NULL, id_type_event INT NOT NULL, date_creation DATE NOT NULL, capacite INT NOT NULL, statut TINYINT DEFAULT 1 NOT NULL, INDEX id_type_event (id_type_event), PRIMARY KEY (id_event)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE habittracker (Id_Habit INT AUTO_INCREMENT NOT NULL, nom_habitude VARCHAR(150) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, emotion_dominantes VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, note_textuelle TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, niveau_energie INT NOT NULL, niveau_stress INT NOT NULL, qualite_sommeil INT NOT NULL, date_creation DATE NOT NULL, id INT NOT NULL, id_journal INT DEFAULT NULL, INDEX fk_habit_journal (id_journal), INDEX fk_habit_user (id), PRIMARY KEY (Id_Habit)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE historique_resultat (id_historique INT AUTO_INCREMENT NOT NULL, id_utilisateur INT NOT NULL, id_test INT NOT NULL, score INT NOT NULL, pourcentage DOUBLE PRECISION NOT NULL, niveau VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_passage DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX IDX_HIST_TEST (id_test), INDEX IDX_HIST_USER (id_utilisateur), PRIMARY KEY (id_historique)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE inscription (id_inscription INT AUTO_INCREMENT NOT NULL, id_evenement INT NOT NULL, date_inscription DATE NOT NULL, email_participant VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, nom_participant VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, INDEX id_evenement (id_evenement), PRIMARY KEY (id_inscription)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE journal_emotionnel (id_journal INT AUTO_INCREMENT NOT NULL, humeur INT NOT NULL, note_textuelle TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_saisie DATE NOT NULL, id INT NOT NULL, INDEX fk_journal_user (id), PRIMARY KEY (id_journal)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE learning_path (id_path INT AUTO_INCREMENT NOT NULL, titre VARCHAR(200) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, date_creation DATE DEFAULT CURRENT_DATE NOT NULL, created_by_id INT NOT NULL, INDEX fk_lp_user (created_by_id), PRIMARY KEY (id_path)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE path_article (id_path INT NOT NULL, id_article INT NOT NULL, ordre INT NOT NULL, INDEX fk_pa_article (id_article), INDEX IDX_C58C384F8074970D (id_path), PRIMARY KEY (id_path, id_article)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE question (id_question INT AUTO_INCREMENT NOT NULL, id_test INT NOT NULL, contenu TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, INDEX IDX_QUESTION_TEST (id_test), PRIMARY KEY (id_question)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE reponse (id_reponse INT AUTO_INCREMENT NOT NULL, id_question INT NOT NULL, contenu VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, points INT DEFAULT 0 NOT NULL, INDEX IDX_REPONSE_QUESTION (id_question), PRIMARY KEY (id_reponse)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE reponse_utilisateur (id_reponse_utilisateur INT AUTO_INCREMENT NOT NULL, id_utilisateur INT NOT NULL, id_question INT NOT NULL, id_reponse INT NOT NULL, date_reponse DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX IDX_RU_USER (id_utilisateur), INDEX IDX_RU_QUESTION (id_question), INDEX IDX_RU_REPONSE (id_reponse), PRIMARY KEY (id_reponse_utilisateur)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE resultat (id_resultat INT AUTO_INCREMENT NOT NULL, id_test INT NOT NULL, id_utilisateur INT NOT NULL, score_total INT NOT NULL, score_max_possible INT NOT NULL, pourcentage DOUBLE PRECISION NOT NULL, resultat VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, interpretation TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, date_passage DATETIME DEFAULT CURRENT_TIMESTAMP, INDEX IDX_RESULTAT_USER (id_utilisateur), UNIQUE INDEX UNIQ_RESULT_TEST_USER (id_test, id_utilisateur), INDEX IDX_E7DB5DE2535F620E (id_test), PRIMARY KEY (id_resultat)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tag (id_tag INT AUTO_INCREMENT NOT NULL, nom VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, UNIQUE INDEX nom (nom), PRIMARY KEY (id_tag)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE test_psychologique (id_test INT AUTO_INCREMENT NOT NULL, titre VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, id_type INT NOT NULL, description TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, nombre_questions INT DEFAULT 0, INDEX IDX_TEST_TYPE (id_type), PRIMARY KEY (id_test)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE tranche_resultat (id_tranche INT AUTO_INCREMENT NOT NULL, id_test INT NOT NULL, score_min INT NOT NULL, score_max INT NOT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, interpretation TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, niveau VARCHAR(50) CHARACTER SET utf8mb4 DEFAULT \'Normal\' COLLATE `utf8mb4_unicode_ci`, INDEX IDX_TRANCHE_TEST (id_test), PRIMARY KEY (id_tranche)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE type_event (id_type_event INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, PRIMARY KEY (id_type_event)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE type_test (id_type INT AUTO_INCREMENT NOT NULL, libelle VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, PRIMARY KEY (id_type)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE ai_recommandation ADD CONSTRAINT `FK_AI_REC_TEST` FOREIGN KEY (id_test) REFERENCES test_psychologique (id_test) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ai_recommandation ADD CONSTRAINT `FK_AI_REC_USER` FOREIGN KEY (id_utilisateur) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT `fk_article_categorie` FOREIGN KEY (id_categorie) REFERENCES categorie (id_categorie) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE article ADD CONSTRAINT `fk_article_user` FOREIGN KEY (auteur_user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_tag ADD CONSTRAINT `fk_at_article` FOREIGN KEY (id_article) REFERENCES article (id_Article) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE article_tag ADD CONSTRAINT `fk_at_tag` FOREIGN KEY (id_tag) REFERENCES tag (id_tag) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_comment ADD CONSTRAINT `fk_cc_parent` FOREIGN KEY (parent_id) REFERENCES community_comment (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_comment ADD CONSTRAINT `fk_cc_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_reaction ADD CONSTRAINT `fk_cr_comment` FOREIGN KEY (comment_id) REFERENCES community_comment (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE community_reaction ADD CONSTRAINT `fk_cr_user` FOREIGN KEY (user_id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE event ADD CONSTRAINT `event_ibfk_1` FOREIGN KEY (id_type_event) REFERENCES type_event (id_type_event) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE habittracker ADD CONSTRAINT `fk_habit_journal` FOREIGN KEY (id_journal) REFERENCES journal_emotionnel (id_journal) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE habittracker ADD CONSTRAINT `fk_habit_user` FOREIGN KEY (id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE historique_resultat ADD CONSTRAINT `FK_HIST_TEST` FOREIGN KEY (id_test) REFERENCES test_psychologique (id_test) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE historique_resultat ADD CONSTRAINT `FK_HIST_USER` FOREIGN KEY (id_utilisateur) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE inscription ADD CONSTRAINT `inscription_ibfk_1` FOREIGN KEY (id_evenement) REFERENCES event (id_event) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE journal_emotionnel ADD CONSTRAINT `fk_journal_user` FOREIGN KEY (id) REFERENCES user (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE learning_path ADD CONSTRAINT `fk_lp_user` FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE path_article ADD CONSTRAINT `fk_pa_article` FOREIGN KEY (id_article) REFERENCES article (id_Article) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE path_article ADD CONSTRAINT `fk_pa_path` FOREIGN KEY (id_path) REFERENCES learning_path (id_path) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE question ADD CONSTRAINT `FK_QUESTION_TEST` FOREIGN KEY (id_test) REFERENCES test_psychologique (id_test) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reponse ADD CONSTRAINT `FK_REPONSE_QUESTION` FOREIGN KEY (id_question) REFERENCES question (id_question) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reponse_utilisateur ADD CONSTRAINT `FK_RU_QUESTION` FOREIGN KEY (id_question) REFERENCES question (id_question) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reponse_utilisateur ADD CONSTRAINT `FK_RU_REPONSE` FOREIGN KEY (id_reponse) REFERENCES reponse (id_reponse) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reponse_utilisateur ADD CONSTRAINT `FK_RU_USER` FOREIGN KEY (id_utilisateur) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resultat ADD CONSTRAINT `FK_RESULTAT_TEST` FOREIGN KEY (id_test) REFERENCES test_psychologique (id_test) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE resultat ADD CONSTRAINT `FK_RESULTAT_USER` FOREIGN KEY (id_utilisateur) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE test_psychologique ADD CONSTRAINT `FK_TEST_TYPE` FOREIGN KEY (id_type) REFERENCES type_test (id_type) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE tranche_resultat ADD CONSTRAINT `FK_TRANCHE_TEST` FOREIGN KEY (id_test) REFERENCES test_psychologique (id_test) ON DELETE CASCADE');
        $this->addSql('DROP TABLE evenement');
        $this->addSql('ALTER TABLE blocked_user DROP FOREIGN KEY FK_718E113719EB6921');
        $this->addSql('ALTER TABLE blocked_user DROP FOREIGN KEY FK_718E113743E8B094');
        $this->addSql('ALTER TABLE blocked_user DROP FOREIGN KEY FK_718E113743E8B094');
        $this->addSql('ALTER TABLE blocked_user CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE blocked_user ADD CONSTRAINT `fk_block_client` FOREIGN KEY (client_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blocked_user ADD CONSTRAINT `fk_block_therapist` FOREIGN KEY (therapist_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX uq_block_pair ON blocked_user (client_id, therapist_id)');
        $this->addSql('DROP INDEX idx_718e113743e8b094 ON blocked_user');
        $this->addSql('CREATE INDEX fk_block_therapist ON blocked_user (therapist_id)');
        $this->addSql('ALTER TABLE blocked_user ADD CONSTRAINT FK_718E113743E8B094 FOREIGN KEY (therapist_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE chat_lock DROP FOREIGN KEY FK_2113064FA76ED395');
        $this->addSql('ALTER TABLE chat_lock CHANGE locked_at locked_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE chat_lock ADD CONSTRAINT `fk_cl_admin` FOREIGN KEY (locked_by) REFERENCES user (id)');
        $this->addSql('ALTER TABLE chat_lock ADD CONSTRAINT `fk_cl_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_cl_user ON chat_lock (user_id, is_active)');
        $this->addSql('CREATE INDEX fk_cl_admin ON chat_lock (locked_by)');
        $this->addSql('ALTER TABLE client_profile DROP FOREIGN KEY FK_D36AEE72A76ED395');
        $this->addSql('ALTER TABLE client_profile DROP FOREIGN KEY FK_D36AEE72A76ED395');
        $this->addSql('ALTER TABLE client_profile CHANGE bio bio TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE client_profile ADD CONSTRAINT `fk_client_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX uniq_d36aee72a76ed395 ON client_profile');
        $this->addSql('CREATE UNIQUE INDEX user_id ON client_profile (user_id)');
        $this->addSql('ALTER TABLE client_profile ADD CONSTRAINT FK_D36AEE72A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE contact_request DROP FOREIGN KEY FK_A1B8AE1E19EB6921');
        $this->addSql('ALTER TABLE contact_request DROP FOREIGN KEY FK_A1B8AE1E43E8B094');
        $this->addSql('ALTER TABLE contact_request DROP FOREIGN KEY FK_A1B8AE1E19EB6921');
        $this->addSql('ALTER TABLE contact_request DROP FOREIGN KEY FK_A1B8AE1E43E8B094');
        $this->addSql('ALTER TABLE contact_request CHANGE message message TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE contact_request ADD CONSTRAINT `fk_cr_client` FOREIGN KEY (client_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact_request ADD CONSTRAINT `fk_cr_therapist` FOREIGN KEY (therapist_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_a1b8ae1e19eb6921 ON contact_request');
        $this->addSql('CREATE INDEX fk_cr_client ON contact_request (client_id)');
        $this->addSql('DROP INDEX idx_a1b8ae1e43e8b094 ON contact_request');
        $this->addSql('CREATE INDEX fk_cr_therapist ON contact_request (therapist_id)');
        $this->addSql('ALTER TABLE contact_request ADD CONSTRAINT FK_A1B8AE1E19EB6921 FOREIGN KEY (client_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE contact_request ADD CONSTRAINT FK_A1B8AE1E43E8B094 FOREIGN KEY (therapist_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E919EB6921');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E943E8B094');
        $this->addSql('ALTER TABLE conversation DROP FOREIGN KEY FK_8A8E26E943E8B094');
        $this->addSql('ALTER TABLE conversation CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT `fk_conv_client` FOREIGN KEY (client_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT `fk_conv_therapist` FOREIGN KEY (therapist_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX uq_conv ON conversation (client_id, therapist_id)');
        $this->addSql('DROP INDEX idx_8a8e26e943e8b094 ON conversation');
        $this->addSql('CREATE INDEX fk_conv_therapist ON conversation (therapist_id)');
        $this->addSql('ALTER TABLE conversation ADD CONSTRAINT FK_8A8E26E943E8B094 FOREIGN KEY (therapist_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F9AC0396');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FF624B39D');
        $this->addSql('ALTER TABLE message CHANGE content content TEXT NOT NULL, CHANGE sent_at sent_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT `fk_msg_conv` FOREIGN KEY (conversation_id) REFERENCES conversation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT `fk_msg_sender` FOREIGN KEY (sender_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_msg_conv ON message (conversation_id, sent_at)');
        $this->addSql('DROP INDEX idx_b6bd307ff624b39d ON message');
        $this->addSql('CREATE INDEX fk_msg_sender ON message (sender_id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF624B39D FOREIGN KEY (sender_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE notification DROP FOREIGN KEY FK_BF5476CAA76ED395');
        $this->addSql('ALTER TABLE notification CHANGE body body TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT `fk_notif_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_notif_user ON notification (user_id, is_read)');
        $this->addSql('ALTER TABLE password_reset_codes DROP FOREIGN KEY FK_D1E1C4C0A76ED395');
        $this->addSql('ALTER TABLE password_reset_codes DROP FOREIGN KEY FK_D1E1C4C0A76ED395');
        $this->addSql('ALTER TABLE password_reset_codes CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE password_reset_codes ADD CONSTRAINT `fk_reset_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_d1e1c4c0a76ed395 ON password_reset_codes');
        $this->addSql('CREATE INDEX idx_reset_user ON password_reset_codes (user_id)');
        $this->addSql('ALTER TABLE password_reset_codes ADD CONSTRAINT FK_D1E1C4C0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784E1CFE6F5');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F778494BDEEB6');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F7784E1CFE6F5');
        $this->addSql('ALTER TABLE report DROP FOREIGN KEY FK_C42F778494BDEEB6');
        $this->addSql('ALTER TABLE report CHANGE details details TEXT DEFAULT NULL, CHANGE context context VARCHAR(20) DEFAULT \'MESSAGING\', CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT `fk_report_reported` FOREIGN KEY (reported_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT `fk_report_reporter` FOREIGN KEY (reporter_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_report_status ON report (status)');
        $this->addSql('DROP INDEX idx_c42f7784e1cfe6f5 ON report');
        $this->addSql('CREATE INDEX idx_report_reporter ON report (reporter_id)');
        $this->addSql('DROP INDEX idx_c42f778494bdeeb6 ON report');
        $this->addSql('CREATE INDEX fk_report_reported ON report (reported_id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F7784E1CFE6F5 FOREIGN KEY (reporter_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE report ADD CONSTRAINT FK_C42F778494BDEEB6 FOREIGN KEY (reported_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE therapist_profile DROP FOREIGN KEY FK_12039482A76ED395');
        $this->addSql('ALTER TABLE therapist_profile DROP FOREIGN KEY FK_12039482A76ED395');
        $this->addSql('ALTER TABLE therapist_profile ADD session_rate INT DEFAULT NULL, ADD available_days VARCHAR(50) DEFAULT NULL, CHANGE bio bio TEXT DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE therapist_profile ADD CONSTRAINT `fk_therapist_user` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX uniq_12039482a76ed395 ON therapist_profile');
        $this->addSql('CREATE UNIQUE INDEX user_id ON therapist_profile (user_id)');
        $this->addSql('ALTER TABLE therapist_profile ADD CONSTRAINT FK_12039482A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE user_settings DROP FOREIGN KEY FK_5C844C5A76ED395');
        $this->addSql('ALTER TABLE user_settings CHANGE theme theme ENUM(\'LIGHT\', \'DARK\') DEFAULT \'LIGHT\', CHANGE font_size font_size ENUM(\'SMALL\', \'NORMAL\', \'LARGE\') DEFAULT \'NORMAL\', CHANGE language language ENUM(\'EN\', \'FR\') DEFAULT \'FR\'');
        $this->addSql('ALTER TABLE user_settings ADD CONSTRAINT `FK_SETTINGS_USER` FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
    }
}
