<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H5rhdzRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h5rhdzR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h5rhdzR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'request' => ['privates', '.errored..service_locator.h5rhdzR.App\\Entity\\ContactRequest', NULL, 'Cannot autowire service ".service_locator.h5rhdzR": it needs an instance of "App\\Entity\\ContactRequest" but this type has been excluded in "config/services.yaml".'],
        ], [
            'request' => 'App\\Entity\\ContactRequest',
        ]);
    }
}
