<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QOIkYUXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qOIkYUX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qOIkYUX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'path' => ['privates', '.errored..service_locator.qOIkYUX.App\\Entity\\LearningPath', NULL, 'Cannot autowire service ".service_locator.qOIkYUX": it needs an instance of "App\\Entity\\LearningPath" but this type has been excluded in "config/services.yaml".'],
            'repo' => ['privates', 'App\\Repository\\LearningPathRepository', 'getLearningPathRepositoryService', true],
        ], [
            'path' => 'App\\Entity\\LearningPath',
            'repo' => 'App\\Repository\\LearningPathRepository',
        ]);
    }
}
