<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TGZ7oSMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TGZ7oSM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'tagRepository' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService', true],
        ], [
            'em' => '?',
            'tagRepository' => 'App\\Repository\\TagRepository',
        ]);

        if (isset($container->privates['.service_locator.TGZ7oSM'])) {
            return $container->privates['.service_locator.TGZ7oSM'];
        }

        return $container->privates['.service_locator.TGZ7oSM'] = $instance;
    }
}
