<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XSD6DHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xSD6D_h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xSD6D_h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pdfExporter' => ['privates', 'App\\Service\\PdfExporter', 'getPdfExporterService', true],
        ], [
            'pdfExporter' => 'App\\Service\\PdfExporter',
        ]);
    }
}
