<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XlPqeViService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xlPqeVi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xlPqeVi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'path' => ['privates', '.errored..service_locator.xlPqeVi.App\\Entity\\LearningPath', NULL, 'Cannot autowire service ".service_locator.xlPqeVi": it needs an instance of "App\\Entity\\LearningPath" but this type has been excluded in "config/services.yaml".'],
        ], [
            'articleRepo' => 'App\\Repository\\ArticleRepository',
            'path' => 'App\\Entity\\LearningPath',
        ]);
    }
}
