<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9d8thgbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9d8thgb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9d8thgb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lock' => ['privates', '.errored..service_locator.9d8thgb.App\\Entity\\ChatLock', NULL, 'Cannot autowire service ".service_locator.9d8thgb": it needs an instance of "App\\Entity\\ChatLock" but this type has been excluded in "config/services.yaml".'],
        ], [
            'lock' => 'App\\Entity\\ChatLock',
        ]);
    }
}
