<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VkNLPvqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vkNLPvq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'articleRepo' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\LearningPathRepository', 'getLearningPathRepositoryService', true],
        ], [
            'articleRepo' => 'App\\Repository\\ArticleRepository',
            'em' => '?',
            'repo' => 'App\\Repository\\LearningPathRepository',
        ]);

        if (isset($container->privates['.service_locator.vkNLPvq'])) {
            return $container->privates['.service_locator.vkNLPvq'];
        }

        return $container->privates['.service_locator.vkNLPvq'] = $instance;
    }
}
