<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y5QrzdZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y5QrzdZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y5QrzdZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'habitude' => ['privates', '.errored..service_locator.y5QrzdZ.App\\Entity\\Journal\\Habitude', NULL, 'Cannot autowire service ".service_locator.y5QrzdZ": it needs an instance of "App\\Entity\\Journal\\Habitude" but this type has been excluded in "config/services.yaml".'],
        ], [
            'habitude' => 'App\\Entity\\Journal\\Habitude',
        ]);
    }
}
