<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArticle2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oYWGn7R.App\Entity\Article' shared service.
     *
     * @return \App\Entity\Article
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oYWGn7R": it needs an instance of "App\\Entity\\Article" but this type has been excluded in "config/services.yaml".');
    }
}
