<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatLockService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9d8thgb.App\Entity\ChatLock' shared service.
     *
     * @return \App\Entity\ChatLock
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.9d8thgb": it needs an instance of "App\\Entity\\ChatLock" but this type has been excluded in "config/services.yaml".');
    }
}
