<?php

namespace ContainerIPx3SRr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConversationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wx1oO5D.App\Entity\Conversation' shared service.
     *
     * @return \App\Entity\Conversation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wx1oO5D": it needs an instance of "App\\Entity\\Conversation" but this type has been excluded in "config/services.yaml".');
    }
}
